# -*- coding: utf-8 -*-
"""round0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYlXCUVnnUMC1LuyvdnpD45yUvJa4HLm
"""

import pandas as pd
import numpy as np

# Load datasets
sentiment = pd.read_csv("fear_greed_index.csv")
trades = pd.read_csv("historical_data.csv")

# Shape
print("Sentiment Shape:", sentiment.shape)
print("Trades Shape:", trades.shape)

# Missing values
print("\nSentiment Missing:\n", sentiment.isnull().sum())
print("\nTrades Missing:\n", trades.isnull().sum())

# Duplicates
print("\nSentiment Duplicates:", sentiment.duplicated().sum())
print("Trades Duplicates:", trades.duplicated().sum())

sentiment.columns = sentiment.columns.str.strip().str.lower()
trades.columns = trades.columns.str.strip().str.lower()

trades.rename(columns={
    'execution price': 'execution_price',
    'size tokens': 'size_tokens',
    'size usd': 'size_usd',
    'closed pnl': 'closed_pnl'
}, inplace=True)

# Convert timestamps
sentiment['timestamp'] = pd.to_datetime(sentiment['timestamp'])
trades['timestamp'] = pd.to_datetime(trades['timestamp'])

# Extract date
sentiment['date'] = sentiment['timestamp'].dt.date
trades['date'] = trades['timestamp'].dt.date

sentiment['date'].duplicated().sum()

sentiment = sentiment.sort_values('timestamp')  # optional (keep latest)
sentiment = sentiment.drop_duplicates(subset='date', keep='last')

sentiment_map = sentiment.set_index('date')['classification']

trades['classification'] = trades['date'].map(sentiment_map)

df = trades.dropna(subset=['classification'])

print(df.shape)
df[['date', 'classification']].head()

# Create mapping
sentiment_map = sentiment.set_index('date')['classification']

# Map instead of merge
trades['classification'] = trades['date'].map(sentiment_map)

# Drop missing
df = trades.dropna(subset=['classification'])

# Win / Loss
df['win'] = df['closed_pnl'] > 0

# Position size (use USD)
df['position_size'] = df['size_usd'].abs()

print(df.columns)

daily_pnl = df.groupby(['account', 'date'])['closed_pnl'].sum().reset_index()

win_rate = df.groupby('account')['win'].mean().reset_index()

avg_size = df.groupby('account')['position_size'].mean().reset_index()

trades_per_day = df.groupby('date').size().reset_index(name='trade_count')

df.columns = df.columns.str.strip().str.lower()

df.rename(columns={
    'closed pnl': 'closed_pnl',
    'size usd': 'size_usd'
}, inplace=True)

df['win'] = df['closed_pnl'] > 0
df['position_size'] = df['size_usd'].abs()

perf = df.groupby('classification').agg({
    'closed_pnl': ['mean', 'std'],
    'win': 'mean'
}).reset_index()

print(perf)

df['cum_pnl'] = df.groupby('account')['closed_pnl'].cumsum()
df['rolling_max'] = df.groupby('account')['cum_pnl'].cummax()
df['drawdown'] = df['cum_pnl'] - df['rolling_max']

drawdown_analysis = df.groupby('classification')['drawdown'].mean()
print(drawdown_analysis)

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x='classification', y='closed_pnl', data=df)
plt.title("PnL Distribution: Fear vs Greed")
plt.show()

behavior = df.groupby('classification').agg({
    'position_size': 'mean',
    'account': 'count'
}).rename(columns={'account': 'trade_count'})

print(behavior)

long_short = df.groupby(['classification', 'side']).size().unstack()
long_short_ratio = long_short.div(long_short.sum(axis=1), axis=0)

print(long_short_ratio)

long_short_ratio.plot(kind='bar', stacked=True)
plt.title("Long vs Short Ratio by Sentiment")
plt.show()

median_size = df['position_size'].median()
df['size_group'] = df['position_size'].apply(
    lambda x: 'High' if x > median_size else 'Low'
)

trade_counts = df['account'].value_counts()
threshold = trade_counts.median()

df['freq_group'] = df['account'].apply(
    lambda x: 'Frequent' if trade_counts[x] > threshold else 'Infrequent'
)

consistency = df.groupby('account')['win'].std().fillna(0)

df['consistency'] = df['account'].map(consistency)

df['cons_group'] = df['consistency'].apply(
    lambda x: 'Consistent' if x < 0.5 else 'Inconsistent'
)

segment_perf = df.groupby(['classification', 'size_group'])['closed_pnl'].mean()
print(segment_perf)

sns.barplot(x='size_group', y='closed_pnl', hue='classification', data=df)
plt.title("Segment Performance")
plt.show()

"""Insight 1

During Greed periods, traders experience significant drawdowns (~ -11,202), indicating that heightened market optimism leads to overexposure and increased downside risk.

Insight 2

The long/short ratio remains balanced (~49% BUY vs ~51% SELL), suggesting that trader success is not driven by directional bias but rather by execution quality and risk management.

Insight 3

High position size trades generate substantially higher average PnL (~93 vs ~4), highlighting that profitability is concentrated among high-risk trades, reinforcing a strong risk-return relationship.
"""



"""## Part C: Actionable Strategies

Strategy 1 (Clear + Data-backed)

Write like this:

Strategy 1: Risk Control During Greed Phases
During Greed periods, traders should limit position sizes and apply stricter stop-loss rules.

This is because the analysis showed significant drawdowns (~ -11,202), indicating that increased optimism leads to overexposure and higher downside risk.

Strategy 2 (Clear + Practical)

Strategy 2: Selective High-Exposure Trading
Traders should allocate larger position sizes only to high-confidence trades, while keeping smaller exposure for low-conviction setups.

This is supported by the observation that high position size trades generate significantly higher PnL (~93 vs ~4), indicating that profitability is concentrated in fewer, high-risk trades.

Additional Rule: Avoid overtrading during Greed phases and prioritize quality trades over quantity, as market direction remains balanced (BUY ~49%, SELL ~51%).

### Bouns
"""

# Prepare data
df_model = df.copy()

# Encode sentiment
df_model['sentiment'] = df_model['classification'].map({'Fear': 0, 'Greed': 1})

# Features
X = df_model[['sentiment', 'position_size']]

# Target
y = df_model['win']

# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prediction
pred = model.predict(X_test)

# Evaluation
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

"""A simple Random Forest model was built to predict trade profitability using sentiment and position size. The model demonstrates that trader behavior combined with market sentiment can provide predictive signals for performance.

BONUS 2: Clustering Traders
"""

from sklearn.cluster import KMeans

# Aggregate per trader
trader_features = df.groupby('account').agg({
    'position_size': 'mean',
    'win': 'mean'
}).reset_index()

# Clustering
kmeans = KMeans(n_clusters=3, random_state=42)
trader_features['cluster'] = kmeans.fit_predict(trader_features[['position_size', 'win']])

print(trader_features.head())

"""BONUS 3: Streamlit Dashboard"""

!pip install streamlit pyngrok

from pyngrok import ngrok

df.to_csv("final_data.csv", index=False)

import streamlit as st
import pandas as pd

st.title("Trader Behavior vs Market Sentiment")

# Load data
df = pd.read_csv("final_data.csv")

# Filter
sentiment_filter = st.selectbox("Select Sentiment", df['classification'].unique())
filtered = df[df['classification'] == sentiment_filter]

st.write("### Data Preview")
st.write(filtered.head())

st.write("### PnL Distribution")
st.bar_chart(filtered['closed_pnl'])

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# st.title("Trader Behavior vs Market Sentiment")
# 
# df = pd.read_csv("final_data.csv")
# 
# sentiment_filter = st.selectbox("Select Sentiment", df['classification'].unique())
# filtered = df[df['classification'] == sentiment_filter]
# 
# st.write("### Data Preview")
# st.write(filtered.head())
# 
# st.write("### PnL Distribution")
# st.bar_chart(filtered['closed_pnl'])

from pyngrok import ngrok

# Add your token
ngrok.set_auth_token("3CiOnZBfmBYUJ7AvWk41wpGwrNE_7wW5w9K1vgvuzYQd3M3gH")

!streamlit run app.py &>/dev/null &

public_url = ngrok.connect(8501)
public_url

